#!/bin/bash

video_file=$1
meta_file=""

error_exit() {
  echo "$1" 1>&2
  exit 1
}

check_video_file_exists() {
	ls ${1}  &> /dev/null || error_exit "Could not find file: ${1}"
}

# Check if the provided video file exists
check_video_file_exists

# Create meta data file name
meta_file="${video_file%%.*}_meta.txt"

# Try to extract the date & create an identifier
DATE_CREATED='2005:10:23 20:06:34.33-05:00 - DEFAULT'
IDENTIFIER='20051023_200634 - DEFAULT'
datec=$(exiftool -q -q -b -keys:CreationDate ${video_file})
if [ ! -z "$datec" ]; then
    DATE_CREATED=$datec
    IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
    IDENTIFIER=${IDENTIFIER// /_}
    IDENTIFIER=${IDENTIFIER//:/}
else
    datec=$(exiftool -q -q -b -CreateDate ${video_file})
    if [ ! -z "$datec" ]; then
        DATE_CREATED=$datec
        IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
        IDENTIFIER=${IDENTIFIER// /_}
        IDENTIFIER=${IDENTIFIER//:/}
    fi
fi

SOFTWARE='Created with FiLMiC Pro6.10.910065 / iOS 14.4 - DEFAULT'
softw=$(exiftool -q -q -b -keys:Software ${video_file})
if [ ! -z "$softw" ]; then
    SOFTWARE=$softw
fi

MAKE='Apple - DEFAULT'
mak=$(exiftool -q -q -b -keys:Make ${video_file})
if [ ! -z "$mak" ]; then
    MAKE=$mak
fi

MODEL='iPhone 11 Pro - DEFAULT'
mod=$(exiftool -q -q -b -keys:Model ${video_file})
if [ ! -z "$mod" ]; then
    MODEL=$mod
fi

GPS='-35.2975906, 149.1012676, 554 - DEFAULT'
gps_coord=$(exiftool -q -q -b -keys:GPSCoordinates ${video_file})
if [ ! -z "$gps_coord" ]; then
    GPS=$gps_coord
fi


rm -f $meta_file &> /dev/null
touch $meta_file
echo "# Generated meta data file for video ${video_file}" >> $meta_file
echo "" >> $meta_file
echo "IDENTIFIER='${IDENTIFIER}'" >> $meta_file
echo "" >> $meta_file
echo "DATE_CREATED='${DATE_CREATED}'" >> $meta_file
echo "" >> $meta_file
echo "MAKE='${MAKE}'" >> $meta_file
echo "MODEL='${MODEL}'" >> $meta_file
echo "SOFTWARE='${SOFTWARE}'" >> $meta_file
echo "GPS='${GPS}'" >> $meta_file
echo "" >> $meta_file
echo "COUNTRY_CODE='CHE'" >> $meta_file
echo "COUNTRY=''" >> $meta_file
echo "STATE=''" >> $meta_file
echo "CITY=''" >> $meta_file
echo "SUBLOCATION=''" >> $meta_file
echo "" >> $meta_file
echo "HEADLINE=''" >> $meta_file
echo "TITLE_SUFFIX=''" >> $meta_file
echo "DESCRIPTION=''" >> $meta_file
echo "COPYRIGHT='Leo Huber'" >> $meta_file