#!/bin/bash

if [ "$(ls -A | grep -i \\.MOV\$)" ]; then echo true; fi 
    for f in *.MOV; do mv "$f" "${f//.MOV/.mov}"; done
fi 

for movie_file in *.mov; do quicktime_generate_metadata ${movie_file}; done;

meta_file="./zzz_meta_data_template.txt"

rm -f $meta_file &> /dev/null
touch $meta_file
echo "# Meta data template" >> $meta_file
echo "" >> $meta_file
echo "MAKE='${MAKE}'" >> $meta_file
echo "MODEL='${MODEL}'" >> $meta_file
echo "SOFTWARE='${SOFTWARE}'" >> $meta_file
echo "GPS='${GPS}'" >> $meta_file
echo "" >> $meta_file
echo "COUNTRY_CODE='CHE'" >> $meta_file
echo "COUNTRY=''" >> $meta_file
echo "STATE=''" >> $meta_file
echo "CITY=''" >> $meta_file
echo "SUBLOCATION=''" >> $meta_file
echo "" >> $meta_file
echo "HEADLINE=''" >> $meta_file
echo "TITLE_SUFFIX=''" >> $meta_file
echo "DESCRIPTION=''" >> $meta_file
echo "COPYRIGHT='Leo Huber'" >> $meta_file