#!/usr/bin/env python3

import os
import glob
import shutil

print("Starting the script...")

# Movie file directory of movies to be copied
test_footage_mov = "/Volumes/Media/video/03_meta_test_footage/"

# File extensions to delete
file_extensions = ['*.mp4', '*.MP4', '*.mov', '*.MOV', '*.mts', '*.MTS']

# Remove the backup directory if it exists
backup_directory = "./backup"
if os.path.exists(backup_directory) and os.path.isdir(backup_directory):
    print(f"Removing backup directory: {backup_directory}")
    shutil.rmtree(backup_directory)
else:
    print("No backup directory found to remove.")

# Recursively search for files with the specified extensions
def find_files_with_extensions(directory, extensions):
    found_files = []
    for ext in extensions:
        found_files.extend(glob.glob(os.path.join(directory, '**', ext), recursive=True))
    return found_files

files = find_files_with_extensions("./", file_extensions)

# Delete each movie file
if len(files) > 0:
    print(f"Found {len(files)} movie files. Deleting them...")
    for file in files:
        os.remove(file)
else:
    print("No movie files found to delete.")

# Copy files from test_footage_mov to current directory
files = find_files_with_extensions(test_footage_mov, file_extensions)
if len(files) > 0:
    print("Copying test footage from: " + test_footage_mov)
    for file in files:
        print(f"Copying file: {file}")
        shutil.copy(file, "./")
else:
    print("No test footage files found to copy.")

# Remove txt files
txt_files = glob.glob('*.txt')
if len(txt_files) > 0:
    print("Removing all .txt files in the current directory...")
    for file in txt_files:
        os.remove(file)
else:
    print("No .txt files found to remove.")