#!/bin/bash

error_exit() {
  echo "$1" 1>&2
  exit 1
}

check_file_exists() {
	ls ${1}  &> /dev/null || error_exit "Could not find file: ${1}"
}

generate_date_filename(){
    
    # Try to extract the date & create an identifier

    # video file
    video_file=$1

    # Check if video file exists
	check_file_exists $video_file

    extension="${video_file##*.}"
    extension="$(tr [A-Z] [a-z] <<< "$extension")"
    model=$(exiftool -s3 -Model ${video_file})

    # check if we are processing a quicktime container
    if [ "$extension" = "mov" ]; then
        # The QuickTime:CreationDate (sic) field you are looking at in Exiftool is a non-standard field that Apple adds to iPhone videos.
        # It records the capture date in local time with a time zone. As far as I know, only iPhones add this field.
        datec=$(exiftool -s3 -CreationDate ${video_file})
        if [ ! -z "$datec" ]; then
            DATE_CREATED=$datec
            IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
            IDENTIFIER=${IDENTIFIER// /_}
            IDENTIFIER=${IDENTIFIER//:/}
            mv $video_file ${IDENTIFIER}.mov
        else
            # The tag CreateDate is available in mov files (for instance the files created with Filmic Pro on Iphone)
            # It contains the local time without time offset
            datec=$(exiftool -s3 -CreateDate ${video_file})
            if [ ! -z "$datec" ]; then
                DATE_CREATED=$datec
                IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
                IDENTIFIER=${IDENTIFIER// /_}
                IDENTIFIER=${IDENTIFIER//:/}
                mv $video_file ${IDENTIFIER}.mov
            fi
        fi
    fi

    # Check if we are processing an mp4 container
    if [ "$extension" = "mp4" ]; then
        if [ "$model" = "Canon EOS R6" ]; then
            # The tag CreateDate is available in MP4 files (at least in the canon R6)
            # It contains the local time without time offset
            datec=$(exiftool -s3 -CreateDate ${video_file})
            if [ ! -z "$datec" ]; then
                DATE_CREATED=$datec
                IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
                IDENTIFIER=${IDENTIFIER// /_}
                IDENTIFIER=${IDENTIFIER//:/}
                mv $video_file ${IDENTIFIER}.mp4
            fi
        fi
    fi

    # Check if we are processing an mts container
    if [ "$extension" = "mts" ]; then
        if [ "$model" = "ILCE-7" ] || [ "$model" = "HDR-CX550VE" ]; then
            # The tag DateTimeOriginal is available in mts files (at least in the sony cameras (ILCE-7, HDR-CX550VE)
            # It contains the local time with time offset
            datec=$(exiftool -s3 -DateTimeOriginal ${video_file})
            if [ ! -z "$datec" ]; then
                DATE_CREATED=$datec
                IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
                IDENTIFIER=${IDENTIFIER// /_}
                IDENTIFIER=${IDENTIFIER//:/}
                mv $video_file ${IDENTIFIER}.mts
            fi
        fi
    fi

}

for movie_file in "$@"
do
    generate_date_filename ${movie_file};
done
