#!/usr/bin/env python3
import glob
import os
from video_slibrary_print_utils import print_green, print_red, print_blue

print_green("Starting the cleanup process of metadate .json files ...")

# Use glob to find all .json and .txt files in the current directory
all_files = glob.glob('./*.json') + glob.glob('./*.txt')
print_green(f"Found {len(all_files)} .json and .txt files to remove.")

# Loop through each file path found
for file_path in all_files:
    print_green(f"Removing file: {file_path}")
    os.remove(file_path)

print_green("Cleanup process completed.")