#!/usr/bin/env python3

import json

meta_file = "zzz_meta_data_template.json"

meta_data = {
    "MAKE": "Canon - DEFAULT",
    "MODEL": "Canon EOS R6 - DEFAULT",
    "GPS": "-35.2975906, 149.1012676, 554 - DEFAULT",
    "CREATOR": "Leo Huber - DEFAULT",
    "COUNTRY_CODE": "CHE - DEFAULT",
    "COUNTRY": "Switzerland - DEFAULT",
    "STATE": "Zurich - DEFAULT",
    "CITY": "Zurich - DEFAULT",
    "SUBLOCATION": "Sublocation - DEFAULT",
    "HEADLINE": "Headline - DEFAULT",
    "TITLE_SUFFIX": "Title Suffix - DEFAULT",
    "DESCRIPTION": "Description - DEFAULT",
    "COPYRIGHT": "Leo Huber - DEFAULT"
}

with open(meta_file, 'w') as f:
    json.dump(meta_data, f, indent=4)
