#!/usr/bin/env python3

meta_file = "zzz_meta_data_template.txt"

with open(meta_file, 'w') as f:
    f.write("# Generated meta data template file\n\n")
    f.write("MAKE='Canon'\n")
    f.write("MODEL='Canon EOS R6'\n")
    f.write("GPS='-35.2975906, 149.1012676, 554'\n\n")
    f.write("CREATOR='Leo Huber'\n")
    f.write("COUNTRY_CODE='CHE'\n")
    f.write("COUNTRY='Switzerland'\n")
    f.write("STATE='Zurich'\n")
    f.write("CITY='Zurich'\n")
    f.write("SUBLOCATION='Sublocation'\n\n")
    f.write("HEADLINE='Headline'\n")
    f.write("TITLE_SUFFIX='title_suffix'\n")
    f.write("DESCRIPTION='Description'\n")
    f.write("COPYRIGHT='Leo Huber'\n")
