#!/bin/bash


error_exit() {
  echo "$1" 1>&2
  exit 1
}

check_file_exists() {
	ls ${1}  &> /dev/null || error_exit "Could not find file: ${1}"
}

generate_metadata(){

    video_file=$1
    meta_file=""

    # Check if video file exists
	check_file_exists $video_file

    # Extract fileame extension: https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash
    extension="${video_file##*.}"

    # Convert to lower case: https://stackoverflow.com/questions/2264428/how-to-convert-a-string-to-lower-case-in-bash
    extension="$(tr [A-Z] [a-z] <<< "$extension")"

    # Extract the model of the camera
    model=$(exiftool -q -q -b -api largefilesupport=1 -Model ${video_file})

    # Create meta data file name
    meta_file="${video_file%%.*}_meta.txt"

    # Try to extract the date & create an identifier
    DATE_CREATED='2005:10:23 20:06:34.33-05:00 - DEFAULT'
    IDENTIFIER='20051023_200634 - DEFAULT'

     # check if we are processing a quicktime container
    if [ "$extension" = "mov" ]; then
        # The QuickTime:CreationDate (sic) field you are looking at in Exiftool is a non-standard field that Apple adds to iPhone videos.
        # It records the capture date in local time with a time zone. As far as I know, only iPhones add this field.
        datec=$(exiftool -q -q -b -api largefilesupport=1 -CreationDate ${video_file})
        if [ ! -z "$datec" ]; then
            DATE_CREATED=$datec
            IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
            IDENTIFIER=${IDENTIFIER// /_}
            IDENTIFIER=${IDENTIFIER//:/}
        else
            # The tag CreateDate is available in mov files (for instance the files created with Filmic Pro on Iphone)
            # It contains the local time without time offset
            datec=$(exiftool -q -q -b -api largefilesupport=1 -CreateDate ${video_file})
            if [ ! -z "$datec" ]; then
                DATE_CREATED=$datec
                IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
                IDENTIFIER=${IDENTIFIER// /_}
                IDENTIFIER=${IDENTIFIER//:/}
            fi
        fi
    fi

    # Check if we are processing an mp4 container
    if [ "$extension" = "mp4" ]; then
        if [ "$model" = "Canon EOS R6" ]; then
            # The tag SubSecCreateDate is available in Canon R6 files
            # It contains the local time without time offset
            datec=$(exiftool -q -q -b -api largefilesupport=1 -SubSecCreateDate ${video_file})
            if [ ! -z "$datec" ]; then
                DATE_CREATED=$datec
                IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
                IDENTIFIER=${IDENTIFIER// /_}
                IDENTIFIER=${IDENTIFIER//:/}
            fi
        else
            # Try the tag CreateDate
            datec=$(exiftool -q -q -b -api largefilesupport=1 -CreateDate ${video_file})
            if [ ! -z "$datec" ]; then
                DATE_CREATED=$datec
                IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
                IDENTIFIER=${IDENTIFIER// /_}
                IDENTIFIER=${IDENTIFIER//:/}
            fi
        fi
    fi

    MAKE='Apple - DEFAULT'
    mak=$(exiftool -q -q -b -api largefilesupport=1 -Make ${video_file})
    if [ ! -z "$mak" ]; then
        MAKE=$mak
    fi

    MODEL='iPhone 11 Pro - DEFAULT'
    mod=$(exiftool -q -q -b -api largefilesupport=1 -Model ${video_file})
    if [ ! -z "$mod" ]; then
        MODEL=$mod
    fi

    GPS='-35.2975906, 149.1012676, 554 - DEFAULT'
    gps_coord=$(exiftool -q -q -b -api largefilesupport=1 -GPSCoordinates ${video_file})
    if [ ! -z "$gps_coord" ]; then
        gps_coord=$(echo $gps_coord | sed 's/ /, /g')
        GPS=$gps_coord
    fi

    COUNTRY_CODE='CHE - DEFAULT'
    cntr_code=$(exiftool -q -q -b -api largefilesupport=1 -CountryCode ${video_file})
    if [ ! -z "$cntr_code" ]; then
        COUNTRY_CODE=$cntr_code
    fi

    COUNTRY='Switzerland - DEFAULT'
    cntr=$(exiftool -q -q -b -api largefilesupport=1 -Country ${video_file})
    if [ ! -z "$cntr" ]; then
        COUNTRY=$cntr
    fi

    CREATOR='Leo Huber - DEFAULT'
    creatr=$(exiftool -q -q -b -api largefilesupport=1 -Creator ${video_file})
    if [ ! -z "$creatr" ]; then
        CREATOR=$creatr
    fi

    STATE='Zurich - DEFAULT'
    state=$(exiftool -q -q -b -api largefilesupport=1 -State ${video_file})
    if [ ! -z "$state" ]; then
        STATE=$state
    fi

    CITY='Zurich - DEFAULT'
    city=$(exiftool -q -q -b -api largefilesupport=1 -City ${video_file})
    if [ ! -z "$city" ]; then
        CITY=$city
    fi

    SUBLOCATION='Sublocation - DEFAULT'
    subloc=$(exiftool -q -q -b -api largefilesupport=1 -Location ${video_file})
    if [ ! -z "$subloc" ]; then
        SUBLOCATION=$subloc
    fi

    HEADLINE='Headline - DEFAULT'
    headl=$(exiftool -q -q -b -api largefilesupport=1 -Headline ${video_file})
    if [ ! -z "$headl" ]; then
        HEADLINE=$headl
    fi

    TITLE_SUFFIX='Title Suffix - DEFAULT'
    titles=$(exiftool -q -q -b -api largefilesupport=1 -Title ${video_file})
    if [ ! -z "$titles" ]; then
        TITLE_SUFFIX=${titles#*_*_}
    fi

    DESCRIPTION='Description - DEFAULT'
    desc=$(exiftool -q -q -b -api largefilesupport=1 -Description ${video_file})
    if [ ! -z "$desc" ]; then
        DESCRIPTION=$desc
    fi

    COPYRIGHT='Leo Huber - DEFAULT'
    copyr=$(exiftool -q -q -b -api largefilesupport=1 -Rights ${video_file})
    if [ ! -z "$copyr" ]; then
        COPYRIGHT=$copyr
    fi

    rm -f $meta_file &> /dev/null
    touch $meta_file
    echo "# Generated meta data file for video ${video_file}" >> $meta_file
    echo "" >> $meta_file
    echo "IDENTIFIER='${IDENTIFIER}'" >> $meta_file
    echo "" >> $meta_file
    echo "DATE_CREATED='${DATE_CREATED}'" >> $meta_file
    echo "" >> $meta_file
    echo "MAKE='${MAKE}'" >> $meta_file
    echo "MODEL='${MODEL}'" >> $meta_file
    echo "GPS='${GPS}'" >> $meta_file
    echo "" >> $meta_file
    echo "CREATOR='${CREATOR}'" >> $meta_file
    echo "COUNTRY_CODE='${COUNTRY_CODE}'" >> $meta_file
    echo "COUNTRY='${COUNTRY}'" >> $meta_file
    echo "STATE='${STATE}'" >> $meta_file
    echo "CITY='${CITY}'" >> $meta_file
    echo "SUBLOCATION='${SUBLOCATION}'" >> $meta_file
    echo "" >> $meta_file
    echo "HEADLINE='${HEADLINE}'" >> $meta_file
    echo "TITLE_SUFFIX='${TITLE_SUFFIX}'" >> $meta_file
    echo "DESCRIPTION='${DESCRIPTION}'" >> $meta_file
    echo "COPYRIGHT='${COPYRIGHT}'" >> $meta_file

}

for movie_file in "$@"
do
    generate_metadata ${movie_file};
done