#!/bin/bash


error_exit() {
  echo "$1" 1>&2
  exit 1
}

check_file_exists() {
  ls ${1}  &> /dev/null || error_exit "Could not find file: ${1}"
}

set_codec_info(){

  video_file=$1
  meta_file=""

  # Check if video file exists
	check_file_exists $video_file

  extension="${video_file##*.}"
  extension="$(tr [A-Z] [a-z] <<< "$extension")"
  model=$(exiftool -q -q -b -api largefilesupport=1 -Model ${video_file})

  # Create meta data file name
  meta_file="${video_file%%.*}_codec.txt"

  # Check if meta file exists and load variables
  check_file_exists $meta_file
  source $meta_file

  # check if we are processing a quicktime or MP4 container
  if [ "$extension" = "mov" ] || [ "$extension" = "mp4" ] ; then
    #  exiftool -overwrite_original -Keys:Comment="${COMMENT}" $video_file &> /dev/null || error_exit "Could not update quicktime keys tags"

    # When updating the field "Copyright Notice", Adobe Bridge updates both, the xmp filed "xmp:Rights" and the field "itemlist:Copyright" with the same value.
    # Therefore ,make sure both fields are updated. The same holds for the fields "xmp:Title" / "itemlist:Title" and "xmp:LogComment" / "itemlist:Comment"
    #exiftool -overwrite_original -itemlist:Comment="${COMMENT}" $video_file &> /dev/null || error_exit "Could not update quicktime keys tags"

    exiftool -api largefilesupport=1 -overwrite_original -xmp:LogComment="${COMMENT}" $video_file &> /dev/null || error_exit "Could not update tag xmp:LogComment"
  fi

}

for movie_file in "$@"
do
    set_codec_info ${movie_file};
done
