#!/bin/bash

error_exit() {
  echo "$1" 1>&2
  exit 1
}

check_video_file_exists() {
	ls ${1}  &> /dev/null || error_exit "Could not find file: ${1}"
}

generate_date_filename(){
    video_file=$1

    # Check if video file exists
    check_video_file_exists $video_file

    # Try to extract the date & create an identifier
    datec=$(exiftool -q -q -b -DateTimeOriginal ${video_file})
    if [ ! -z "$datec" ]; then
        DATE_CREATED=$datec
        IDENTIFIER=$(echo $DATE_CREATED | cut -c1-19)
        IDENTIFIER=${IDENTIFIER// /_}
        IDENTIFIER=${IDENTIFIER//:/}
        mv $video_file ${IDENTIFIER}.mts
    fi
}

for movie_file in *.mts; do
    generate_date_filename ${movie_file};
done;